[alias]
moonbase = " build --release -p axtend --no-default-features --features moonbase-native"
moonbase-benchmarks = " build --release -p axtend --no-default-features --features moonbase-runtime-benchmarks"
moonbase-betanet = " build --release -p axtend --no-default-features --features moonbase-native,betanet-native"
moonbase-tracing = " build --release -p axtend --features moonbase-native-tracing"
moonriver = " build --release -p axtend --no-default-features --features moonriver-native"
moonriver-betanet = " build --release -p axtend --no-default-features --features moonriver-native,betanet-native"
moonriver-axctest = " build --release -p axtend --no-default-features --features moonriver-native,axctest-native"
axtend = " build --release -p axtend --no-default-features --features axtend-native"
axtend-betanet = " build --release -p axtend --no-default-features --features axtend-native,betanet-native"
