[alias]
moonbase = " build --release -p axtend --no-default-features --features moonbase-native"
moonbase-benchmarks = " build --release -p axtend --no-default-features --features moonbase-runtime-benchmarks"
moonbase-rococo = " build --release -p axtend --no-default-features --features moonbase-native,rococo-native"
moonbase-tracing = " build --release -p axtend --features moonbase-native-tracing"
moonriver = " build --release -p axtend --no-default-features --features moonriver-native"
moonriver-rococo = " build --release -p axtend --no-default-features --features moonriver-native,rococo-native"
moonriver-kusama = " build --release -p axtend --no-default-features --features moonriver-native,kusama-native"
axtend = " build --release -p axtend --no-default-features --features axtend-native"
axtend-rococo = " build --release -p axtend --no-default-features --features axtend-native,rococo-native"
